"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-30 08:59:20.713973
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import algotrade.db.models


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('hash_prev', sa.String(length=64), nullable=False),
    sa.Column('hash_self', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=False),
    sa.Column('trades', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('ts', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'ts')
    )
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bars_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_bars_ts'), ['ts'], unique=False)

    op.create_table('config_versions',
    sa.Column('version', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('risk', sa.JSON(), nullable=False),
    sa.Column('strategy', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=32), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ts', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_ts'), ['ts'], unique=False)

    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('positions_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('realized', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('drawdown_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equity_snapshots_ts'), ['ts'], unique=False)

    op.create_table('fills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('ts', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('charges', sa.JSON(), nullable=False),
    sa.Column('charges_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fills_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_ts'), ['ts'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('publisher', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('published_at', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('credibility', sa.Float(), nullable=False),
    sa.Column('scored', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_published_at'), ['published_at'], unique=False)

    op.create_table('order_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('ts', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=False),
    sa.Column('to_state', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('trigger_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stop', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('parent_order_id', sa.String(length=64), nullable=True),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('created_at', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)

    op.create_table('positions',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('stop', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('initial_stop', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('highest_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('opened_at', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('check_name', sa.String(length=48), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_ts'), ['ts'], unique=False)

    op.create_table('sentiment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('is_material', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.String(length=240), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('published_at', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('credibility', sa.Float(), nullable=False),
    sa.Column('created_at', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id', 'symbol')
    )
    with op.batch_alter_table('sentiment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_news_id'), ['news_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_symbol'), ['symbol'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('bar_ts', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_ts'), ['ts'], unique=False)

    op.create_table('system_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', algotrade.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_state')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_ts'))
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))

    op.drop_table('signals')
    with op.batch_alter_table('sentiment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentiment_symbol'))
        batch_op.drop_index(batch_op.f('ix_sentiment_news_id'))

    op.drop_table('sentiment')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_ts'))

    op.drop_table('risk_events')
    op.drop_table('positions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_orders_state'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))

    op.drop_table('order_events')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_published_at'))

    op.drop_table('news_items')
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fills_ts'))
        batch_op.drop_index(batch_op.f('ix_fills_symbol'))
        batch_op.drop_index(batch_op.f('ix_fills_order_id'))

    op.drop_table('fills')
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equity_snapshots_ts'))

    op.drop_table('equity_snapshots')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_ts'))
        batch_op.drop_index(batch_op.f('ix_decisions_symbol'))

    op.drop_table('decisions')
    op.drop_table('config_versions')
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bars_ts'))
        batch_op.drop_index(batch_op.f('ix_bars_symbol'))

    op.drop_table('bars')
    op.drop_table('backtest_runs')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
